AllCops:
  TargetRubyVersion: 2.6.1
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
Rails:
  Enabled: true
Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb

Layout:
  Style/EmptyLinesAroundBlockBody:
    Enabled: false

  Style/EmptyLinesAroundModuleBody:
    Enabled: false

  Style/EmptyLinesAroundClassBody:
    Enabled: false

  Style/EmptyLinesAroundMethodBody:
    Enabled: false
