version: "3.3"
services:
  db:
    image: postgres:11.2-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
